### ISSUE TITLE
how create api for sanjab admin panel

### ISSUE THREAD

**Issue by jafarpishdadi** [sanjabteam/sanjab#5]
thanks for this package
how create api from this admin panel

example

localhost/api/product

show json array of product

please help me thanks

**Comment by amir9480** [comment]
Hello.

Thanks for using sanjab. Glad to see that.

Actually sanjab is just for creating admin panels, **not API**.
You should implement API yourself.

If you just want to implement something just for admins with AJAX you can use 
/admin/modules/MODULE_ROUTE
with
```
Accept: application/json
```
Header.

It is also possible to use CRUD controllers and implement your API generator based on CRUD controllers.
```php
use Sanjab;

foreach (Sanjab::controllers() as $controller) {
    if (is_subclass_of($controller, 'Sanjab\Controllers\CrudController')) {
         $model = $controller::properties()->property('model');
         // ...
    }
}
```

**Comment by jafarpishdadi** [comment]
Thank you for your answer
I know php but learning  the basics of Laravel
Thank you for completing the steps of create api sanjab table with example or refrence
