### ISSUE TITLE
installing sanjab

### ISSUE THREAD

**Issue by anditsung** [sanjabteam/sanjab#9]
hello.. please update the installation page

it still using laravel 6 
but when i instal it on 6 it will not work at all

right now im using the latest laravel

after add require for sanjab got this message

Deprecation Notice: Class Sanjab\Observers\SettingObserver located in ./vendor/sanjabteam/sanjab/src/Observer/SettingObserver.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/Cellar/composer/1.9.1/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Sanjab\Observers\SettingTranslationObserver located in ./vendor/sanjabteam/sanjab/src/Observer/SettingTranslationObserver.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/Cellar/composer/1.9.1/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class HTMLPurifier_Language_en_x_test located in ./vendor/ezyang/htmlpurifier/library/HTMLPurifier/Language/classes/en-x-test.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/Cellar/composer/1.9.1/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by amir9480** [comment]
Hi @anditsung.
It looks like related to composer v2.0 rather than Laravel version.

I gonna update my composer today to see what gonna happen.

**Comment by amir9480** [comment]
@anditsung 
I found the bug and fixed it.

Install sanjab version 0.1.4 and everything works fine.

Also, Htmlpurifier error is an open issue here:
https://github.com/ezyang/htmlpurifier/issues/246
